pod 'AFNetworking'
pod 'WSProgressHUD', '~> 1.0.5'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SVPullToRefresh'
pod 'PKRevealController'
pod 'RongCloudIMKit'
pod 'RSKImageCropper', '~> 1.2.0'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'FDFullscreenPopGesture', '~> 1.1'